---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: concourse-boot-sample
  
outputs:
  - name: foo-app
  
run:
  path: concourse-boot-sample/build.sh